### PR TITLE
bump 1.1.0

### PR DESCRIPTION
**Pull request by RafaelGSS**

### CODE REVIEW

**Comment by RafaelGSS** [comment]
@simoneb since we're going to rename the package, there's no need to migrate `node-clinic-heap-profiler` to org, don't you think?

**Comment by simoneb** [comment]
Yes, makes sense, but we still need somebody to deprecate the old package and since James is the only contributor on npm he's the one who can do it

**Comment by RafaelGSS** [comment]
Ok. Shall I wait for the package deprecation before release this?

**Comment by simoneb** [comment]
We can go ahead

**Pull request merged**
